# Generated by Django 4.1 on 2023-07-26 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatsAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('bedroom', models.PositiveIntegerField()),
                ('livingroom', models.PositiveIntegerField()),
                ('bathroom', models.PositiveIntegerField()),
                ('kitchen', models.PositiveIntegerField()),
                ('contact_number', models.CharField(max_length=15)),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('images', models.FileField(blank=True, null=True, upload_to='flats_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('persons', models.PositiveIntegerField()),
                ('profession', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houserent.flatsavailable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houserent.bookings')),
            ],
        ),
    ]
