# Generated by Django 4.1 on 2023-07-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houserent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatsavailable',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
