# Generated by Django 4.0.1 on 2023-09-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houserent', '0002_alter_flatsavailable_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatsavailable',
            name='slugs',
            field=models.SlugField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='flatsavailable',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
