# Generated by Django 4.0.1 on 2023-09-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houserent', '0003_flatsavailable_slugs_alter_flatsavailable_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatsavailable',
            name='images',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
