# Generated by Django 4.0.1 on 2023-09-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houserent', '0004_alter_flatsavailable_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatsavailable',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='flatsavailable',
            name='slugs',
            field=models.SlugField(unique=True),
        ),
    ]
