# Generated by Django 4.0.1 on 2023-10-06 11:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houserent', '0005_alter_flatsavailable_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatsavailable',
            name='slugs',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
