# Generated by Django 4.0.1 on 2023-10-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houserent', '0006_alter_flatsavailable_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatsavailable',
            name='slugs',
            field=models.SlugField(unique=True),
        ),
    ]
