# Generated by Django 4.1 on 2023-11-27 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houserent', '0008_alter_flatsavailable_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatsavailable',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Id'),
        ),
    ]
