# Generated by Django 4.1 on 2023-11-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houserent', '0010_rename_price_flatsavailable_required_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatsavailable',
            old_name='required_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='flatsavailable',
            name='recieved_price',
        ),
        migrations.AddField(
            model_name='flatsavailable',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='flatsavailable',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flatsavailable',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
