# Generated by Django 4.1 on 2023-11-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houserent', '0011_rename_required_price_flatsavailable_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatsavailable',
            name='post_status',
        ),
        migrations.AddField(
            model_name='booked',
            name='booked_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booked',
            name='status',
            field=models.CharField(choices=[('r', 'requested'), ('a', 'approved'), ('s', 'successful'), ('x', 'rejected')], default='r', max_length=50),
        ),
    ]
