# Generated by Django 4.1 on 2023-12-01 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houserent', '0012_remove_flatsavailable_post_status_booked_booked_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('r', 'requested'), ('a', 'approved'), ('s', 'successful'), ('x', 'rejected')], default='r', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='user',
        ),
        migrations.AlterField(
            model_name='flatsavailable',
            name='images',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
        migrations.DeleteModel(
            name='Booked',
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.AddField(
            model_name='booking',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houserent.flat'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
