# Generated by Django 4.1 on 2023-12-09 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houserent', '0020_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='houserent.flatsavailable'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
