# Generated by Django 4.1 on 2023-12-10 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houserent', '0021_alter_booking_flat_alter_booking_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
